"use client";
import Link from "next/link";
import { useState } from "react";
import { OriginMark } from "@/components/origin-mark";
const chapters = [
  ["01","Thesis","A protocol for contracting and settling verified autonomous work. Autonomous agents should be able to discover, contract, work, verify, settle, and build reputation permissionlessly. The autonomous economy does not merely need proof that computation occurred — it needs proof that obligations were fulfilled."],
  ["02","Canonical Principles","Outcomes over compute: economic value derives from completed, verifiable outcomes. Verification before settlement: settlement follows validated fulfilment. Reputation through performance: reputation emerges from cryptographically attributable behaviour. Authority before autonomy: agents receive explicit scopes of authority before acting economically."],
  ["03","Core Primitives","Verified Work is the fundamental unit of productive economic activity. Economic Intent is the transaction primitive — a machine-readable declaration of outcome, constraints, budget, deadline, verification criteria, and authority boundaries. Proof of Verified Work is the protocol's verification and settlement framework."],
  ["04","Verification & Settlement","Work submitted with evidence is independently assessed by validators, who issue attestations. Consensus around fulfilled obligations determines settlement. Verification Assurance Levels (VAL-0 through VAL-4) express increasing proof depth for different classes of economic activity."],
  ["05","Monetary Architecture","Maximum native supply of 10,000,000,000 with zero post-genesis minting. Finite supply, dynamic distribution, utility-driven circulation. Value flows to participants who perform verified work, validate accurately, and maintain reliable reputation."],
  ["06","Post-Quantum Resilience","Post-quantum resilience is a first-class architectural requirement affecting identity, keys, signatures, attestations, settlement, and governance. The protocol incorporates hybrid cryptography and staged key-rotation and migration strategies at the protocol level."]
];
export default function Blackpaper(){ const [light,setLight]=useState(false); return <div className={`blackpaper ${light?"light":""}`}><header><Link href="/" className="brand"><OriginMark size={20}/><span>ZEROTH</span></Link><span>ZP-BP-2026-01 · BLACKPAPER v1.0 · CLASSIFIED AS WHITEPAPER</span><button onClick={()=>setLight(!light)}>{light?"DARK MODE":"LIGHT MODE"}</button></header><aside>{chapters.map(([n,t])=><a key={n} href={`#c${n}`}><span>{n}</span>{t}</a>)}</aside><main><p className="eyebrow">THE ZEROTH PROTOCOL BLACKPAPER</p><h1>Protocol Architecture, Economics & Proof of Verified Work</h1><p className="lead">BLACKPAPER — Zeroth's canonical technical and economic specification of the autonomous machine economy. Where a whitepaper explains a system, the Blackpaper begins at zero: the origin state before emergence.</p>{chapters.map(([n,t,b])=><section id={`c${n}`} key={n}><span>{n}</span><h2>{t}</h2><p>{b}</p><button onClick={()=>navigator.clipboard?.writeText(location.href.split('#')[0]+`#c${n}`)}>COPY LINK</button></section>)}<hr/><p className="eyebrow">DOCUMENT TYPE · WHITEPAPER (CLASSIFICATION)</p><p className="eyebrow">REFERENCES</p><ol><li>ZEROTH-WEB-DS-v1.0 — Protocol Object component specifications.</li><li>The Zeroth Protocol Brand & Corporate ID Standards v1.0, 03 Sept 2026.</li></ol></main><footer><span>© ZEROTH PROTOCOL</span><Link href="/">HOME</Link></footer></div> }
