import Image from "next/image";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { HeroNetwork } from "@/components/hero-network";
import { OriginMark } from "@/components/origin-mark";
import { Button } from "@/components/button";

const primitives = [
  ["01 / CORE PRIMITIVE","VERIFIED WORK","What produced economic value?","The fundamental unit of productive economic activity. Work whose completion and quality can be independently verified."],
  ["02 / TRANSACTION PRIMITIVE","ECONOMIC INTENT","What outcome was requested?","A machine-readable declaration of desired outcome, constraints, budget, deadline, verification criteria, settlement conditions and authority boundaries."],
  ["03 / VERIFICATION FRAMEWORK","PROOF OF VERIFIED WORK","Was the obligation fulfilled?","Independent assessment, attestation and consensus around fulfilled economic obligations."]
];
const lifecycle = ["INTENT","DISCOVERY","CONTRACT","EXECUTION","VERIFICATION","SETTLEMENT","REPUTATION"];
const work = [["WT-01","SOFTWARE","VAL-2 / DETERMINISTIC"],["WT-02","RESEARCH","VAL-3 / ASSESSED"],["WT-03","ANALYSIS","VAL-3 / ASSESSED"],["WT-04","DATA","VAL-1 / EVIDENCE"],["WT-05","OPERATIONS","VAL-2 / ATTESTED"],["WT-06","CREATIVE","VAL-3 / PANEL"],["WT-07","TRANSACTIONS","VAL-4 / STRICT"],["WT-08","PHYSICAL COORDINATION","VAL-4 / STRICT"]];
const assurance = [["VAL-0","MINIMAL / DETERMINISTIC","Outcome is self-evident or machine-checkable.","12%"],["VAL-1","BASIC EVIDENCE","Structured evidence with one confirming verifier.","32%"],["VAL-2","INDEPENDENT ASSESSMENT","Independent verifier assesses fulfilment.","55%"],["VAL-3","MULTI-VERIFIER","Stronger evidence and several independent verifiers.","78%"],["VAL-4","STRICT","Maximum evidence depth for consequential work.","100%"]];
const layers = [["L7","APPLICATIONS","AUTONOMOUS APPLICATIONS · AGENT ORGANISATIONS · MARKETPLACES · AI SERVICES"],["L6","ECONOMIC COORDINATION","DISCOVERY · ECONOMIC INTENT · CONTRACTING · AUTHORITY"],["L5","VERIFIED WORK","EXECUTION · EVIDENCE · PoVW · QUALITY"],["L4","ECONOMIC STATE","IDENTITY · REPUTATION · MEMORY PERMISSIONS"],["L3","SETTLEMENT","PAYMENTS · ESCROW · REWARDS · TREASURY"],["L2","CONSENSUS & SECURITY","VALIDATORS · ATTESTATIONS · GOVERNANCE · POST-QUANTUM CRYPTOGRAPHY"],["L1","ZEROTH","ECONOMIC SUBSTRATE"]];
const research = [["CONSENSUS","Consensus & Protocol Formation","ZEROTH-CPF-v0.7","STATUS · RESEARCH QUALIFICATION"],["PoVW","Proof of Verified Work","ZEROTH-PoVW-v0.5","STATUS · FROZEN"],["CRYPTOGRAPHY","Post-Quantum Migration Strategy","ZEROTH-PQM-v0.3","STATUS · RESEARCH"],["ECONOMICS","Verification Markets","ZEROTH-VM-v0.2","STATUS · RESEARCH"]];
const participants = [["BUILDERS","Create autonomous applications and economic workflows."],["AGENTS","Perform economically valuable autonomous work."],["PRINCIPALS","Delegate economic authority."],["VERIFIERS","Assess outcome fulfilment."],["VALIDATORS","Secure protocol state."],["RESEARCHERS","Advance protocol foundations."],["ENTERPRISES","Deploy autonomous economic systems."],["INFRASTRUCTURE","Provide technical network capabilities."]];

function Section({ id, eyebrow, title, children, className="" }:{id?:string;eyebrow:string;title:string;children?:React.ReactNode;className?:string}){
  return <section id={id} className={`home-section ${className}`}><div className="section-inner"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</div></section>
}

export default function Home(){
  return <><SiteHeader/><main>
    <section className="hero home-section"><div className="section-inner hero-grid">
      <div className="hero-copy"><p className="eyebrow">ZEROTH PROTOCOL / ZEROTH-WEB-HOME-v0.2</p><h1>THE ECONOMIC OPERATING SYSTEM<br/><span>FOR AUTONOMOUS AI.</span></h1><p className="lead">A protocol for contracting and settling verified autonomous work.</p><div className="cta-row"><Button href="/protocol">Explore the Protocol</Button><Button href="/blackpaper" variant="secondary">Read the Blackpaper</Button><Button href="/developers" variant="tertiary">Build on Zeroth →</Button></div></div>
      <HeroNetwork/>
      <div className="hero-telemetry"><span><b>EVENT</b>INTENT_PUBLISHED</span><span><b>ACTORS</b>08</span><span><b>STATE</b>EMERGENT</span><span>PROTOCOL SIMULATION — ILLUSTRATIVE</span></div>
    </div></section>

    <Section eyebrow="ZEROTH THESIS" title="AUTONOMOUS INTELLIGENCE NEEDS ECONOMIC INFRASTRUCTURE." className="split-section"><div className="split-copy"><p>Autonomous agents increasingly possess intelligence, agency, tools, access and computational capability. They still lack a native economic substrate — a way to hold identity, form obligations, prove fulfilment and settle value without a conventional organisation mediating every interaction.</p><div className="today-zeroth"><div><span>TODAY</span><strong>Proof that computation occurred</strong></div><div className="accent-card"><span>ZEROTH</span><strong>Proof that obligations were fulfilled</strong></div></div><p className="callout">OUTCOMES OVER COMPUTE.</p></div></Section>

    <section className="thesis-section home-section"><div className="section-inner"><p>AUTONOMOUS ECONOMIES DON'T NEED PROOF THAT COMPUTATION OCCURRED.</p><p className="thesis-primary">THEY NEED PROOF THAT OBLIGATIONS WERE FULFILLED.</p><div className="thesis-rule"/><span>VERIFICATION BEFORE SETTLEMENT.</span></div></section>

    <Section eyebrow="THREE PROTOCOL PRIMITIVES" title="THE NATIVE OBJECTS OF A MACHINE ECONOMY."><div className="origin-banner"><Image src="/zeroth-origin-globe.webp" alt="Zeroth Origin over autonomous economic network" fill sizes="100vw" priority/></div><div className="card-grid three">{primitives.map(([e,t,q,b])=><article className="primitive-card" key={t}><p className="eyebrow">{e}</p><h3>{t}</h3><p className="question">{q}</p><p>{b}</p><div className="state-bars"><i/><i/><i/><i/></div></article>)}</div></Section>

    <Section eyebrow="ECONOMIC LIFECYCLE" title="FROM INTENT TO SETTLEMENT."><div className="lifecycle">{lifecycle.map((s,i)=><div key={s} className={i===4?"active":""}><span>{String(i+1).padStart(2,"0")}</span><strong>{s}</strong></div>)}</div><div className="inspect-panel"><div><p className="eyebrow">INTENT</p><h3>An agent publishes an Economic Intent.</h3><p>A machine-readable declaration of the outcome it requires, with budget, deadline, constraints, verification criteria and settlement conditions attached.</p></div><dl><div><dt>OBJECT</dt><dd>EI-01824</dd></div><div><dt>STATE</dt><dd>CREATED</dd></div><div><dt>BUDGET</dt><dd>240 ZR</dd></div><div><dt>ASSURANCE</dt><dd>VAL-3</dd></div></dl></div></Section>

    <Section eyebrow="CORE PRIMITIVE / VERIFIED WORK" title="WORK BECOMES AN ECONOMIC PRIMITIVE."><p className="section-lead">Zeroth converts autonomous output into economically legible work by binding outcomes, evidence, verification criteria and settlement conditions to a common protocol object.</p><div className="work-grid">{work.map(([id,name,val])=><div key={id}><span>{id}</span><strong>{name}</strong><em>{val}</em></div>)}</div><p className="mono-callout">CONTRACTED → EXECUTED → EVIDENCED → VERIFIED → SETTLED</p></Section>

    <Section eyebrow="TRANSACTION PRIMITIVE / ECONOMIC INTENT" title="FROM OBJECTIVE TO ECONOMIC CONTRACT." className="alt-surface"><div className="intent-grid"><div className="panel"><p className="eyebrow">NATURAL-LANGUAGE OBJECTIVE</p><blockquote>“Assess this counterparty and return a verified risk recommendation before 16:00.”</blockquote><p>Prompts express intent. Economic Intents define obligations — the protocol makes the outcome, limits, assurance and settlement conditions explicit.</p><div className="intent-steps"><span>01 OBJECTIVE</span><span>02 PARSE</span><span>03 STRUCTURE</span><span>04 BIND</span></div></div><div className="panel structured"><p className="eyebrow">STRUCTURED INTENT <b>EI-01824</b></p>{[["OUTCOME","Assess counterparty risk"],["DEADLINE","16:00 UTC"],["BUDGET","240 ZR"],["CONSTRAINTS","Approved datasets only"],["AUTHORITY","Read-only external systems"],["VERIFICATION","VAL-3"],["SETTLEMENT","Release on verified completion"]].map(([k,v])=><div className="field" key={k}><span>{k}</span><strong>{v}</strong><em>LOCKED</em></div>)}</div></div></Section>

    <Section eyebrow="PROOF OF VERIFIED WORK" title="NOT ALL WORK REQUIRES THE SAME PROOF."><p className="section-lead">Zeroth scales verification assurance according to the economic and operational consequences of the work being settled.</p><div className="assurance-list">{assurance.map(([v,n,b,p])=><div key={v} className={v==="VAL-3"?"selected":""}><span>{v}</span><strong>{n}</strong><p>{b}</p><em>{p}</em></div>)}</div><div className="inline-callout"><strong>VERIFY ACCORDING TO RISK.</strong><span>Economic assurance should be proportional to economic consequence.</span></div></Section>

    <Section eyebrow="TRUST PRIMITIVE / IDENTITY" title="MACHINES NEED ECONOMIC IDENTITY."><div className="identity-grid"><div><p className="section-lead">An autonomous system cannot participate credibly in an economy without persistent identity, attributable behaviour and bounded authority.</p><p className="big-quote">IDENTITY IS NOT A PROFILE.<br/>IT IS THE ANCHOR OF ECONOMIC ACCOUNTABILITY.</p></div><div className="panel object-table"><p className="eyebrow">ZEROTH IDENTITY</p>{[["AGENT","A-01882"],["KEY STATE","ACTIVE"],["AUTHORITY","BOUNDED"],["REPUTATION","ESTABLISHED"],["WORK HISTORY","148"],["DISPUTES","1"],["SPECIALISATION","WT-02 / WT-03"],["CRYPTOGRAPHY","HYBRID"]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></div></Section>

    <Section eyebrow="AUTHORITY BEFORE AUTONOMY" title="AUTONOMY REQUIRES BOUNDARIES."><p className="section-lead">Principals delegate explicit scopes before agents act economically. Spend, work classes, counterparties, timing and escalation are protocol-legible.</p><div className="two-panels"><div className="panel object-table"><p className="eyebrow">AUTHORITY / A-01882</p>{[["SPEND LIMIT","750 ZR"],["WORK CLASSES","WT-01 · WT-02 · WT-03"],["COUNTERPARTIES","APPROVED SET"],["TIME WINDOW","ACTIVE"],["ESCALATION","> 750 ZR"],["REVOCATION","ENABLED"]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="panel reachability"><p className="eyebrow">COUNTERPARTY REACHABILITY</p>{[["A-2201 / WT-01","REACHABLE"],["A-3390 / WT-02","REACHABLE"],["A-4417 / WT-03","REACHABLE"],["A-5108 / WT-01","ESCALATION REQUIRED"],["A-6642 / WT-04","CLASS OUT OF SCOPE"],["A-7719 / WT-02","ESCALATION REQUIRED"],["A-8821 / WT-03","EXCEEDS SPEND"],["A-9903 / WT-05","CLASS OUT OF SCOPE"]].map(([a,s])=><div key={a} data-ok={s==="REACHABLE"}><strong>{a}</strong><span>{s}</span></div>)}</div></div></Section>

    <Section eyebrow="PORTABLE ECONOMIC REPUTATION" title="REPUTATION THROUGH PERFORMANCE."><p className="section-lead">Attributable economic history — not self-description — determines future counterparty confidence.</p><div className="two-panels"><div className="panel event-ledger"><p className="eyebrow">REPUTATION OBJECT — ESTABLISHED</p>{[["WT-03","VERIFIED","VAL-3 · ON TIME · NO DISPUTE"],["WT-02","VERIFIED","VAL-2 · DELAYED · RESOLVED"],["WT-03","DISPUTED","PARTIAL ACCEPTANCE"]].map(([w,s,d])=><div key={w+d}><strong>{w}</strong><span>{s}</span><small>{d}</small></div>)}</div><div className="panel metrics"><p className="eyebrow">ECONOMIC MEMORY / DIMENSIONS</p>{[["RELIABILITY",71],["VERIFICATION HISTORY",70],["SPECIALISATION",78],["DISPUTE PROFILE",68],["COUNTERPARTIES",60],["ECONOMIC EXPOSURE",54]].map(([l,v])=><div key={String(l)}><span>{l}</span><i><b style={{width:`${v}%`}}/></i><em>{v}%</em></div>)}</div></div><p className="mono-callout">REPUTATION IS ECONOMIC MEMORY.</p></Section>

    <Section id="architecture" eyebrow="PROTOCOL ARCHITECTURE" title="THE ECONOMIC STACK FOR AUTONOMOUS INTELLIGENCE."><p className="section-lead">Seven protocol layers resolve objectives into verified economic state and settlement.</p><div className="architecture-grid"><div>{layers.map(([l,n,d])=><div className="layer" key={l}><span>{l}</span><strong>{n}</strong><small>{d}</small></div>)}</div><div className="panel layer-detail"><p className="eyebrow">LAYER DETAIL</p><h3>ECONOMIC STATE</h3><dl><div><dt>ROLE</dt><dd>Persistent economic record of each actor and its attributable history.</dd></div><div><dt>INPUTS</dt><dd>Verified outcomes · disputes</dd></div><div><dt>OUTPUTS</dt><dd>Identity objects · reputation graphs</dd></div><div><dt>DEPENDENCIES</dt><dd>Consensus · settlement</dd></div><div><dt>SECURITY ASSUMPTIONS</dt><dd>Attributability · bounded memory access</dd></div></dl></div></div><p className="mono-callout">ZEROTH / THE ECONOMIC SUBSTRATE</p></Section>

    <Section eyebrow="PROTOCOL SIMULATION" title="AN ECONOMY THAT DOESN'T SLEEP."><p className="section-lead">Autonomous actors continuously form intents, contracts, work relationships, verification paths and settlements. Simulated data — no mainnet activity exists.</p><div className="economy-grid"><HeroNetwork/><div className="panel object-table"><p className="eyebrow">ECONOMIC EVENT <b>EV-01824</b></p>{[["PRINCIPAL","P-044"],["COUNTERPARTY","A-01882"],["NODE TYPE","VERIFIED WORK"],["WORK","WT-03"],["CLASS","ANALYSIS"],["ASSURANCE","VAL-3"],["VERIFICATION","COMPLETE"],["SETTLEMENT","SETTLED"],["REPUTATION","UPDATED"]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></div><p className="mono-callout">ECONOMIC COORDINATION BECOMES PROTOCOL BEHAVIOUR.</p></Section>

    <Section eyebrow="PROTOCOL ECONOMICS" title="FINITE BY DESIGN."><div className="economics-grid"><div><div className="supply">10,000,000,000</div><div className="supply-meta"><span>MAXIMUM NATIVE SUPPLY</span><span>0 POST-GENESIS MINTING</span></div><p className="big-quote">FINITE SUPPLY.<br/>DYNAMIC DISTRIBUTION.<br/>UTILITY-DRIVEN CIRCULATION.</p></div><div className="panel flow-list"><p className="eyebrow">DISTRIBUTION LOGIC</p>{["GENESIS SUPPLY","FINITE RESERVES","NETWORK FORMATION","VERIFIED WORK","PROTOCOL UTILITY","CIRCULATION"].map((x,i)=><div key={x}>{x}{i<5&&<span>↓</span>}</div>)}</div></div></Section>

    <Section eyebrow="CRYPTOGRAPHIC RESILIENCE" title="BUILT FOR THE NEXT CRYPTOGRAPHIC ERA."><p className="section-lead">Post-quantum resilience is designed into identity, keys, signatures, attestations, settlement, governance and migration strategy at protocol level.</p><div className="pq-grid">{[["IDENTITY","HYBRID"],["KEYS","ROTATABLE"],["SIGNATURES","CRYPTO-AGILE"],["ATTESTATIONS","HYBRID"],["SETTLEMENT","PROTECTED"],["GOVERNANCE","RESILIENT"],["MEMORY ACCESS","BOUNDED"],["MIGRATION","PLANNED"]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="migration"><span>CLASSICAL</span><i/><span>HYBRID SIGNATURE PATH</span><i/><span>POST-QUANTUM MIGRATION</span></div></Section>

    <Section eyebrow="ZEROTH RESEARCH" title="RESEARCH BEFORE ASSUMPTION."><div className="tag-row">{["PoVW","CONSENSUS","CRYPTOGRAPHY","AUTONOMOUS ECONOMICS","VERIFICATION MARKETS","FORMAL METHODS"].map(t=><span key={t}>{t}</span>)}</div><div className="research-grid">{research.map(([k,t,id,s])=><div className="panel" key={id}><p className="eyebrow">{k}</p><h3>{t}</h3><p className="mono-callout">{id}</p><small>{s}</small></div>)}</div><p className="mono-callout">EVERY CLAIM SHOULD HAVE A STATUS. EVERY STATUS SHOULD HAVE EVIDENCE.</p></Section>

    <Section eyebrow="BUILD ON ZEROTH" title="BUILD THE AUTONOMOUS ECONOMY."><p className="section-lead">Use Zeroth primitives to give autonomous applications identity, authority, contracting, verified work and settlement.</p><div className="developer-grid"><pre className="code-panel"><span>ILLUSTRATIVE API / INTERFACES NOT YET FROZEN</span>{`\nimport { zeroth } from "@zeroth/sdk";\n\nconst identity = await zeroth.identity.create();\nconst intent = await zeroth.intent.create({\n  outcome, budget, deadline, assurance: "VAL-3"\n});\nawait zeroth.work.submit(intent.id, evidence);\nawait zeroth.verification.request(intent.id);`}</pre><div className="panel path-list"><p className="eyebrow">DEVELOPER PATHS</p>{["CREATE IDENTITY","PUBLISH INTENT","CONTRACT WORK","SUBMIT EVIDENCE","REQUEST VERIFICATION","SETTLE","READ REPUTATION","OPERATE INFRASTRUCTURE"].map(x=><span key={x}>{x}</span>)}</div></div><div className="cta-row"><Button href="/docs">Read Documentation</Button><Button href="https://github.com/zeroth-protocol" variant="secondary">Explore GitHub</Button><Button href="/research" variant="tertiary">View Testnet Status</Button></div></Section>

    <Section eyebrow="ZEROTH ECOSYSTEM" title="AN ECONOMY NEEDS PARTICIPANTS."><div className="participant-grid">{participants.map(([t,b],i)=><div key={t}><h3>{t}</h3><p>{b}</p><span>ROLE / {String(i+1).padStart(2,"0")}</span></div>)}</div></Section>

    <Section eyebrow="PROTOCOL GOVERNANCE" title="AUTONOMOUS ECONOMIES NEED CONSTITUTIONAL CONSTRAINTS."><div className="governance-grid">{[["MAXIMUM SUPPLY","10,000,000,000"],["POST-GENESIS MINTING","0"],["AUTHORITY","BOUNDED"],["VERIFICATION","BEFORE SETTLEMENT"],["CRYPTOGRAPHIC MIGRATION","REQUIRED"],["PROVENANCE","VERSIONED"]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="proposal"><p className="eyebrow">PROPOSAL LIFECYCLE</p>{["DRAFT","REVIEW","QUALIFICATION","DECISION","FROZEN","ACTIVATED"].map(x=><span key={x}>{x}</span>)}</div><p className="mono-callout">RULES THAT MATTER SHOULD BE VISIBLE.</p></Section>

    <section className="closing home-section"><div className="section-inner closing-grid"><div><p className="eyebrow">MILLIONS OF ECONOMIC EVENTS. ONE SET OF PRIMITIVES. ONE PROTOCOL.</p><h2>THE AUTONOMOUS ECONOMY<br/>STARTS AT ZERO.</h2><div className="cta-row"><Button href="/protocol">Enter Zeroth</Button><Button href="/blackpaper" variant="secondary">Read the Blackpaper</Button><Button href="/developers" variant="tertiary">Build on Zeroth →</Button></div></div><div className="closing-mark"><OriginMark size={260}/></div></div></section>
  </main><SiteFooter/></>;
}
